version: "3.8"

services:
  message-server:
    container_name: garden-land
    build: .
    ports:
      - 6001:6001
    expose:
      - 6001
    networks:
      - garden-land

networks:
  garden-land:
    name: garden-land
    external: true